# Generated by Django 4.1.3 on 2023-06-03 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
